import { Quote } from "lucide-react";
import { Eyebrow } from "../shared/Eyebrow";
import { Button } from "../shared/Button";

const testimonials = [
  { quote: `Our team used to lose weeks re-reading the same documents and rediscovering the same sources. With Orvene, every source, note and finding lives in one organized workspace. We've stopped repeating work and started building on it, and our projects move forward with far more momentum.`, name: "Karthikeyan Subramaniam", role: "R&D Manager", avatar: "/avatar-2.png", featured: true },
  { quote: `The evidence-to-conclusion traceability is the feature I rely on most. I can open any finding and see exactly which sources support it, so internal reviews are faster and our conclusions stand up to scrutiny. It has changed how confidently we present our work.`, name: "Thenmozhi Rajendran", role: "Senior Research Scientist", avatar: "/avatar-1.png" },
  { quote: "Research history used to be scattered across inboxes, folders and personal notes. Orvene gives us a complete activity trail with a record of what changed, when and why. New team members get up to speed in days instead of weeks, and institutional knowledge no longer walks out the door.", name: "Aravindan Selvakumar", role: "Knowledge Manager", avatar: "/avatar-3.png" },
  { quote: "Search and filtering across projects, sources and findings is quick and intuitive. I can pull together an evidence-backed brief in a fraction of the time it used to take, and I always know where each data point came from.", name: "Madhumitha Vijayakumar", role: "Business Analyst", avatar: "/avatar-4.png" },
];

export function Testimonials() { return <section id="testimonials" className="testimonials section-sage"><div className="container"><div className="section-intro"><div><Eyebrow>TESTIMONIALS</Eyebrow><h2>Trusted by teams who turn research into <em>results.</em></h2></div><p>See how research teams use Orvene to trace every finding back to its evidence, with one organized workspace from first source to final conclusion.</p></div><div className="testimonial-grid">{testimonials.map(({ quote, name, role, avatar, featured }) => <figure className={`testimonial-card ${featured ? "featured" : ""}`} key={name}><Quote className="quote-mark" size={26} strokeWidth={1.2} /><blockquote>{quote}</blockquote><figcaption><img className="testimonial-avatar" src={avatar} alt={name} /><span className="testimonial-person"><strong>{name}</strong><small>{role}</small></span></figcaption></figure>)}<div className="testimonial-cta"><div><Eyebrow>YOUR TURN</Eyebrow><h3>See it on your own questions.</h3><p>Bring one live investigation. We will show you how it holds up.</p></div><Button to="/product">Explore the platform</Button></div></div><div className="testimonial-metrics">{[["1,200+", "Research projects tracked"], ["38%", "Less time hunting for context"], ["4.9 / 5", "Onboarding satisfaction"]].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div></section>; }